services:
  frontend:
    image: xhc2/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:80"
    environment:
      - VITE_GRAPHQL_URI=http://101.37.205.231:8082/graphql
      - VITE_SERVER_URI=http://101.37.205.231:8082
    restart: unless-stopped